### ISSUE TITLE
I have problem ( Error ) =(

### ISSUE THREAD

**Issue by EleonBuntarev** [Divran/e2imageloader#2]
Hello! I hope that you will answer me, would be grateful (time has passed a lot already = D). I really want to use this magic code, but I ran into a problem that I cannot solve for a week = (
It lies in the lack of image loading, he only writes to me (" Found 0 loadsharing E2s! Loading image 'http://i.imgur.com/xn4cYl4.png' ")
I uploaded the PHP code to Xampp, sort of set it up, but it didn't work = (

**Comment by Divran** [comment]
See #1

**Comment by EleonBuntarev** [comment]
> See #1

sorry? but it is'not help =(

**Comment by Divran** [comment]
Click the link and read it. The exact solution to the problem is there.

**Comment by EleonBuntarev** [comment]
Of course I'm sorry, but this doesn't work! Can you-can you check if I did everything right? I have attached a video file. I can attach what you ask to any host ... = (

**Comment by EleonBuntarev** [comment]
it isn't because i play on server (on local didn't work too)

**Comment by EleonBuntarev** [comment]
If this is really my dumb mistake, I'm sorry

**Comment by Divran** [comment]
The link I gave you says the following

> If it says it's 0x0, you need to make sure your server hosting the php script is accessible and working. Check the url near the top of the e2 and make sure it's pointing at the correct server. If you want to make sure the server is working correctly, go to this line https://github.com/Divran/e2imageloader/blob/master/imageloader.txt#L183 and uncomment it. The url which the e2 uses to fetch the image data will then be visible in chat. Copy paste this url into your browser and make sure you are getting data from it. If you get no image data, you need to fix your php server host.

I am going to write the same exact thing but in steps:

1. Check the URL at the top of the E2 and make sure it's pointing at the correct server (your PHP server).
2. Go to line 183 of the E2 and uncomment it so that it prints the URL to chat.
3. Copy the URL that is printed to chat and paste it in your web browser.
4. If you do not get any image data in your web browser, then your PHP server is broken and you will need to fix it.

This is the solution, and it was already written in the link I gave you. I can't help you any more than this.

**Comment by EleonBuntarev** [comment]
Image, that use for example didn't work, too =(
![Screenshot_114](https://user-images.githubusercontent.com/75780222/101755115-8c422900-3ae5-11eb-944f-5445f08bc848.png)

**Comment by EleonBuntarev** [comment]
> The link I gave you says the following
> 
> > If it says it's 0x0, you need to make sure your server hosting the php script is accessible and working. Check the url near the top of the e2 and make sure it's pointing at the correct server. If you want to make sure the server is working correctly, go to this line https://github.com/Divran/e2imageloader/blob/master/imageloader.txt#L183 and uncomment it. The url which the e2 uses to fetch the image data will then be visible in chat. Copy paste this url into your browser and make sure you are getting data from it. If you get no image data, you need to fix your php server host.
> 
> I am going to write the same exact thing but in steps:
> 
> 1. Check the URL at the top of the E2 and make sure it's pointing at the correct server (your PHP server).
> 2. Go to line 183 of the E2 and uncomment it so that it prints the URL to chat.
> 3. Copy the URL that is printed to chat and paste it in your web browser.
> 4. If you do not get any image data in your web browser, then your PHP server is broken and you will need to fix it.
> 
> This is the solution, and it was already written in the link I gave you. I can't help you any more than this.

okey =/ Thank very much
